/* Generated by tools/build_schools.py -- do not edit by hand. */
window.BOARD_DATA = window.BOARD_DATA || {};
window.BOARD_DATA["bloorview-sa"] = {"board":"Bloorview SA","ref":{},"schools":[{"board":"Bloorview SA","boardNo":"80012","fr":false,"id":"417556","name":"Bloorview School Authority","grades":"JK-8","addr":"150 Kilgour Rd","city":"Toronto","postal":"M4G1R8","phone":"416-424-3831","web":"http://www.bloorviewschool.ca","enrol":65,"lat":43.71881,"lon":-79.3725,"ctx":{"ell":0,"newc":0,"sped":0,"gift":0,"lowinc":0,"nodeg":0},"res":{},"why":{}}]};
