/* Generated by tools/build_schools.py -- do not edit by hand. */
window.BOARD_DATA = window.BOARD_DATA || {};
window.BOARD_DATA["cheo-sa"] = {"board":"CHEO SA","ref":{},"schools":[{"board":"CHEO SA","boardNo":"80055","fr":false,"id":"428833","name":"CHEO School","grades":"JK-4","addr":"395 Smyth Rd","city":"Ottawa","postal":"K1H8L2","phone":"613-737-0871","web":"www.octc.ca","enrol":null,"lat":45.39904,"lon":-75.6534,"ctx":{"ell":null,"newc":null,"sped":null,"gift":null,"lowinc":null,"nodeg":null},"res":{},"why":{}}]};
