/* Generated by tools/build_schools.py -- do not edit by hand. */
window.BOARD_DATA = window.BOARD_DATA || {};
window.BOARD_DATA["grandview-sa"] = {"board":"Grandview SA","ref":{},"schools":[{"board":"Grandview SA","boardNo":"80020","fr":false,"id":"425729","name":"Grandview School","grades":"JK-8","addr":"600 Townline Rd S","city":"Oshawa","postal":"L1H0C8","phone":"905-576-8403","web":"https://grandviewkids.ca/grandview-school/","enrol":50,"lat":43.89175,"lon":-78.8082,"ctx":{"ell":0,"newc":0,"sped":100,"gift":0,"lowinc":0,"nodeg":0},"res":{},"why":{}}]};
