/* Generated by tools/build_schools.py -- do not edit by hand. */
window.BOARD_DATA = window.BOARD_DATA || {};
window.BOARD_DATA["kidsability-e-a"] = {"board":"KidsAbility E A","ref":{},"schools":[{"board":"KidsAbility E A","boardNo":"80039","fr":false,"id":"301825","name":"KidsAbility School","grades":"JK-3","addr":"500 Hallmark Dr","city":"Waterloo","postal":"N2K3P5","phone":"519-886-8886","web":"http://www.kidsability.ca/en/school","enrol":75,"lat":43.49853,"lon":-80.5184,"ctx":{"ell":20,"newc":0,"sped":100,"gift":0,"lowinc":0,"nodeg":0},"res":{},"why":{}}]};
